name: Deploy Flask application

on:
  push:
    branches:
      - master
      


jobs:
    build-and-push:
      name: Build and Push  Docker image
      runs-on: ubuntu-latest

      steps:
        # checkout the code
        - name: Checkout code
          uses: actions/checkout@v4

        # log in to dockerhub
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image 
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest -f Season2/Day6/Dockerfile Season2/Day6
            docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    deploy:
      name: Deploy Application
      runs-on: ubuntu-latest
      needs: build-and-push

      steps:
        - name: Pull and run Docker container
          run: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
            docker run -d -p 5000:5000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

        # validate the application
        - name: Validate application
          run: |
            sleep 10
            curl -f http://localhost:5000 || exit 1

    notify:
      name: Send Email notification
      runs-on: ubuntu-latest
      needs: deploy

      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 'smtp.example.com'
          server_port: '587'
          username: peakyjohn526@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Deployment Status'
          body: |
            The Flask application has been successfully deployed on Github Runners
          to: peakyjohn526@gmail.com
          from: peakyjohn526@gmail.com
          
      